### ISSUE TITLE
Doesen't work.

### ISSUE THREAD

**Issue by NoSadBeHappy** [shaanaliyev/r-placer#1]
Here is my link: https://shaanaliyev.github.io/r-placer/place.html?url=https%3A%2F%2Fimgur.com%2F55zZko4&x=0&y=10

When I use it, it blinks a page that I can't see, then just goes back to https://shaanaliyev.github.io/r-placer/

**Comment by shaanaliyev** [comment]
The image URL should end with the correct image format, such as .png, .webp, etc. 

Right click that imgur image and say "open in a new tap" then copy the image URL.
